### ISSUE TITLE
[Bug] jest.spyOn does not work

### ISSUE THREAD

**Issue by nkgrnkgr** [storybookjs/jest#17]
### Describe the bug

"spyOn" does not work correctly when using "jest.spyOn". 

It displays the following error
```jest.spyOn(...).mockReturnValue is not a function```

### Steps to reproduce the behavior

Write the following code to start Storybook.

#### Test.tsx
```tsx
export const Test = () => {
  const handleClick = () => {
    redirect();
  };

  return (
    <div>
      <div>hoge</div>
      <button onClick={handleClick}>click</button>
    </div>
  );
};
```

#### Test.stories.tsx
```tsx
import { jest } from "@storybook/jest";
import * as location from "./location";

export default {
  component: Test,
} as ComponentMeta<typeof Test>;

export const TestStory: ComponentStoryObj<typeof Test> = {
  play: async ({ canvasElement }) => {
    jest.spyOn(location, "redirect");

    const canvas = within(canvasElement);
    const button = await canvas.findByRole("button");
    userEvent.click(button);
  },
};
```

#### location.ts
```typescript
export const redirect = () => {
  window.location.href = "https://www.google.com";
};
```

https://github.com/nkgrnkgr/storybook-jest-example/blob/master/src/stories/Test.stories.tsx

### Expected behavior

"redirect" function can be mocked up.

### Screenshots and/or logs

<img width="1493" alt="スクリーンショット 2022-05-25 17 31 16" src="https://user-images.githubusercontent.com/17094072/170218147-4963fa62-fa7c-42fb-a139-da0ec8f13f9c.png">

### Environment

 - OS: MacOS 12.3.1
 - Node.js version: v17.5.0
 - NPM version: v8.4.1
 - Browser (if applicable):  Google Chrome
 - Browser version (if applicable): 101.0.4951.64

**Comment by yannbf** [comment]
Hey everyone! In Storybook 8, this package functionality has been integrated to a new package called `@storybook/test`, which uses Vitest APIs for an improved experience. When upgrading to Storybook 8 with `npx storybook@latest upgrade`, you will get prompted and will get an automigration for the new package. Please migrate when you can! Thanks a lot <3
