### ISSUE TITLE
[Bug] expect().toBeInstanceOf() is not working

### ISSUE THREAD

**Issue by AndreiSoroka** [storybookjs/jest#18]
### Describe the bug

expect().toBeInstanceOf() not working

### Steps to reproduce the behavior

```ts
Test.play = async ({ canvasElement, args }) => {
  const $inputName = canvasElement.querySelector('[data-test-el="form-define-attribute-name"]');
  // working
  if (!($inputName instanceof HTMLInputElement)) {
    throw new Error('$inputName is not HTMLInputElement');
  }
  // not working
  // await expect($inputName).toBeInstanceOf(HTMLInputElement);
  ...
}
```
### Expected behavior

should be passed

### Screenshots and/or logs

<img width="470" alt="image" src="https://user-images.githubusercontent.com/6079139/172405839-252ae79d-b503-40fe-a86e-ab4cbb74a888.png">

### Environment

 - OS: MacOs
 - Node.js version: v16.14.0
 - NPM version: 8.3.1
 - Browser (if applicable): chrome
 - Browser version (if applicable): 102.0.5005.61 (Official Build) (arm64)

**Comment by yannbf** [comment]
Hey everyone! In Storybook 8, this package functionality has been integrated to a new package called `@storybook/test`, which uses Vitest APIs for an improved experience. This issue should be solved or maybe it's not applicable anymore.

When upgrading to Storybook 8 with `npx storybook@latest upgrade`, you will get prompted and will get an automigration for the new package. Please migrate when you can! Thanks a lot <3
