### ISSUE TITLE
Expect() will not compile [Bug]

### ISSUE THREAD

**Issue by david-morris** [storybookjs/jest#19]
### Describe the bug

Expect won't compile, whether exported from `@storybook/jest` or `@storybook/expect`.

### Steps to reproduce the behavior

This happens whenever I try to load a story with expect().

### Screenshots and/or logs

If applicable, add screenshots and/or logs to help explain your problem.
![image](https://user-images.githubusercontent.com/5530960/180810318-ba89fcdf-b7df-4a6c-970d-17026b8c521a.png)

### Environment

 - OS: ubuntu on docker on windows, all bolted together with vscode
 - Node.js version: 16.14.0
 - Yarn version: 1.22.17

### Additional context
I'm using `swc` via `storybook-addon-swc` (and have already gotten rid of babel configs). 
I'm using `react-i18n` which means I have a lot of components which define a local variable `t`.

**Comment by IanVS** [comment]
@david-morris could you provide a link to a reproduction?  That will make it much easier to help troubleshoot this issue.

**Comment by david-morris** [comment]
@IanVS It's a proprietary repo, so I'll start work on reproducing in a clean or scrubbed environment. In the meantime, are there any logs, etc., which I could paste which would help?

**Comment by IanVS** [comment]
Thanks, but I think the only thing that will really help here is a reproduction, unfortunately.  You can create a new project using `npm create vite@latest` and then run `npx sb init` to get the basic bones set up, then add a test and swc to see if that alone causes the issue, then maybe react-i18n to see if it's a conflict there.  Thanks for reporting and for the help to troubleshoot it.

**Comment by david-morris** [comment]
Hmm, I'm having a lot of trouble reproducing this bug.
I think it might have to do with some of the webpack configs in the create-react-app preset? My project is an nx/next.js monorepo while my reproduction is via create-react-app.

I've noticed that if I disable the SWC loader in the `storybook-addon-swc` options, it will run with lots of webpack warnings (but not on all my stories), but explicitly enabling the SWC loader in my create-react-app repo doesn't reproduce the bug.

I'm going to check what the create-react-app preset does to Webpack and Babel as I try to reproduce this. Does @storybook/jest do anything to Webpack and/or Babel?

**Comment by yannbf** [comment]
Hey everyone! In Storybook 8, this package functionality has been integrated to a new package called `@storybook/test`, which uses Vitest APIs for an improved experience. This issue should be solved or maybe it's not applicable anymore.

When upgrading to Storybook 8 with `npx storybook@latest upgrade`, you will get prompted and will get an automigration for the new package. Please migrate when you can! Thanks a lot <3
