### ISSUE TITLE
[Feature] Release version with Jest 28

### ISSUE THREAD

**Issue by IanVS** [storybookjs/jest#20]
Now that the test-runner will [soon support](https://github.com/storybookjs/test-runner/pull/154) jest 28, it would be great to have a new version of `@storybook/jest` (and `@storybook/expect`) that also use jest 28 as well, to avoid the problems that jest 27 has with using `global`, making it difficult to run in the browser.

**Comment by KubaJastrz** [comment]
Can we include this in Storybook 7.0? Test-runner has already been updated to support Jest 28. Do you need any help?

**Comment by itsezc** [comment]
Is there any workaround in the mean time until we wait for an update?

**Comment by IanVS** [comment]
Thanks for pushing https://github.com/storybookjs/expect/pull/12 across the line, @ghengeveld!  What remains to do here to pull it in?

In the meantime, I suppose we can use overrides in our package.json to start using it and _testing_ it out (pun intended).

**Comment by IanVS** [comment]
You bring up good points, I'll give it some thought.  Off the cuff, I'll say that I see the global polyfill as a workaround, not a permanent solution.  Vite does not polyfill node globals, so therefore right now it's possible for stories to work fine if they use `global`, but the app could break because it doesn't have the same polyfill that storybook is adding hidden behind the scenes.  

I did try using an `override`, and indeed I found trouble with the test-runner, though I wasn't able to track it down to where exactly it came from.  

>addon-interactions uses jest-mock 27 as a direct dependency, will that clash somehow? given that it's tied to the monorepo, we can't make a breaking change to upgrade it.

That's too bad, I wish we would have taken care of this before storybook 7's release.  I was quite looking forward to removing the `global` polyfill for vite storybook, and I was under the impression that the reason we weren't really prioritizing these satellite repos was that we would be able to take care of them after the 7.0 launch.  Hopefully we can figure all of this out for 8.0.

**Comment by IanVS** [comment]
I guess this can be closed, now that 0.2.0 includes jest 28, right?

**Comment by kasperpeulen** [comment]
It still uses 27 from `jest-mock`, we tried to upgrade it, but it breaks browser compatibility.

**Comment by IanVS** [comment]
@kasperpeulen it looks like it also uses `@storybook/expect` version `27.5.2-0`, even though `@types/jest` has been updated to `28.1.3`.  Isn't that a potential issue?

**Comment by yannbf** [comment]
@IanVS The new version of this library will update `@storybook/expect` to `28.1.3`!

**Comment by IanVS** [comment]
🙌 Now we just have to figure out jest-mock, I guess.

**Comment by IanVS** [comment]
For now, when I need mocks, I'm using jest-mock 28 directly, and using:

```ts
import { ModuleMocker } from 'jest-mock';

const mock = new ModuleMocker(window);
```

And that's working fine in my stories.

**Comment by yannbf** [comment]
Hey everyone! In Storybook 8, this package functionality has been integrated to a new package called `@storybook/test`, which uses Vitest APIs for an improved experience. This issue should be solved or maybe it's not applicable anymore.

When upgrading to Storybook 8 with `npx storybook@latest upgrade`, you will get prompted and will get an automigration for the new package. Please migrate when you can! Thanks a lot <3
