### ISSUE TITLE
[bug] Can't resolve '@testing-library/jest-dom/matchers'

### ISSUE THREAD

**Issue by CHE1RON** [storybookjs/jest#40]
**Describe the bug**
In their latest versions, `@storybook/testing-library` and `@storybook/jest` give me the following error:

```
Module not found: Error: Can't resolve '@testing-library/jest-dom/matchers' in '/path/to/node_modules/@storybook/jest/dist'
Did you mean 'matchers.js'?
BREAKING CHANGE: The request '@testing-library/jest-dom/matchers' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

I also have installed the following related packages:

```
"@testing-library/jest-dom": "^6.0.1"
"@testing-library/react": "^14.0.0"
```

**To Reproduce**
1. Install Storybook along with `@storybook/testing-library` and `@storybook/jest`
2. Run Storybook

**System**
```
  System:
    OS: macOS 13.3
    CPU: (8) arm64 Apple M2
  Binaries:
    Node: 20.4.0 - ~/.nvm/versions/node/v20.4.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.7.2 - ~/.nvm/versions/node/v20.4.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.96
    Edge: 114.0.1823.55
    Safari: 16.4
  npmPackages:
    @storybook/addon-a11y: ^7.3.2 => 7.3.2
    @storybook/addon-coverage: ^0.0.9 => 0.0.9
    @storybook/addon-essentials: ^7.3.2 => 7.3.2
    @storybook/addon-interactions: ^7.3.2 => 7.3.2
    @storybook/addon-links: ^7.3.2 => 7.3.2
    @storybook/addon-styling: ^1.3.6 => 1.3.6
    @storybook/addon-viewport: ^7.3.2 => 7.3.2
    @storybook/blocks: ^7.3.2 => 7.3.2
    @storybook/jest: ^0.2.1 => 0.2.1
    @storybook/node-logger: ^7.3.2 => 7.3.2
    @storybook/preset-create-react-app: ^7.3.2 => 7.3.2
    @storybook/react: ^7.3.2 => 7.3.2
    @storybook/react-webpack5: ^7.3.2 => 7.3.2
    @storybook/test-runner: ^0.13.0 => 0.13.0
    @storybook/testing-library: ^0.2.0 => 0.2.0
```

**Comment by YTakahashii** [comment]
I am using "@testing-library/jest-dom: ^5.17.0" and having the same problem.

The workaround I have found is to downgrade the version to `@storybook/jest@0.1.0`.

```js
  "devDependencies": {
    "@storybook/addon-actions": "^7.3.2",
    "@storybook/addon-essentials": "^7.3.2",
    "@storybook/addon-interactions": "^7.3.2",
    "@storybook/addon-links": "^7.3.2",
    "@storybook/react": "^7.3.2",
    "@storybook/react-webpack5": "^7.3.2",
    "@storybook/testing-library": "^0.2.1",
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^12.1.5",
    "@testing-library/user-event": "^14.4.3",
}
```

**Comment by IanVS** [comment]
Could one of you make a reproduction, perhaps using https://storybook.new?

**Comment by Akurganow** [comment]
I think my case is related to this issue.
When running test-storybook, all tests crash with the error `TypeError: expect.extend: 'default' is not a valid matcher. Must be a function, is "object"`.
Downgrade to `"@storybook/jest": "^0.2.1"` solve the problem

**Comment by IanVS** [comment]
A reproduction would be very helpful to find out what is happening here.

**Comment by IanVS** [comment]
It looks like so far everyone with this error is using the react-webpack5 builder.  I'm using vite, which might be why I don't see this error.  Does webpack require fully-specified imports (i.e. extensions must be included)?  Does it not support package.json `exports` maps?

**Comment by IanVS** [comment]
@YTakahashii Yes, `@storybook/jest@0.2.x` uses jest-dom 6.  So, you could either update your own jest-dom, or you'll need to stay with the older storybook/jest package.

**Comment by yannbf** [comment]
Hey everyone! In Storybook 8, this package functionality has been integrated to a new package called `@storybook/test`, which uses Vitest APIs for an improved experience. This issue should be solved or maybe it's not applicable anymore.

When upgrading to Storybook 8 with `npx storybook@latest upgrade`, you will get prompted and will get an automigration for the new package. Please migrate when you can! Thanks a lot <3
