### ISSUE TITLE
[bug] Running test-storybook causes an error

### ISSUE THREAD

**Issue by Akurganow** [storybookjs/jest#45]
**Describe the bug**
After update `@storybook/jest` to `0.2.2` all tests crashes with error `TypeError: expect.extend: 'default' is not a valid matcher. Must be a function, is "object"`

**To Reproduce**
1. Install or update `@storybook/jest` to 0.2.2
2. Create story and simple test using `expect` from`@storybook/jest` 
3. Run `test-storybook`
5. See error `TypeError: expect.extend: 'default' is not a valid matcher. Must be a function, is "object"`

**Expected behavior**
Test are passed

**System**
```
Environment Info:

  System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
  Browsers:
    Chrome: 117.0.5938.88
    Edge: 117.0.2045.31
    Safari: 16.6
  npmPackages:
    @storybook/addon-essentials: ^7.4.1 => 7.4.2 
    @storybook/addon-interactions: ^7.4.2 => 7.4.2 
    @storybook/addon-links: ^7.4.1 => 7.4.2 
    @storybook/blocks: ^7.4.1 => 7.4.2 
    @storybook/jest: ^0.2.2 => 0.2.2 
    @storybook/react: ^7.4.1 => 7.4.2 
    @storybook/react-webpack5: ^7.4.1 => 7.4.2 
    @storybook/test-runner: ^0.13.0 => 0.13.0 
    @storybook/testing-library: ^0.2.1 => 0.2.1 


```

**Additional context**
Downgrading `@storybook/jest` to `0.2.1` solve the problem

**Comment by IanVS** [comment]
Could you please share the result of `npm ls @testing-library/jest-dom`?

**Comment by Akurganow** [comment]
@IanVS 
```
webext@0.0.1 /Users/akurganow/Projects/webext
└─┬ @storybook/jest@0.2.1
  └── @testing-library/jest-dom@5.17.0

```
```
webext@0.0.1 /Users/akurganow/Projects/webext
└─┬ @storybook/jest@0.2.2
  └── @testing-library/jest-dom@6.1.3
```

**Comment by ChrisW-B** [comment]
What transformer are you using in jest.config.js? I'm curious if this is the same issue as mine in #44

**Comment by Akurganow** [comment]
I don't use jest directly, I don't have my own config, I use storybook/jest

**Comment by scagood** [comment]
I had to make this patch:
```diff
diff --git a/dist/index.js b/dist/index.js
index 75ebbdec13f0b042aac312d7b5a9a5376c593f82..bfa3c423d988a01aaf8e120ff6524e44d9cdc0c4 100644
--- a/dist/index.js
+++ b/dist/index.js
@@ -393,4 +393,4 @@ var matchers = __toESM(require("@testing-library/jest-dom/matchers")), mock = __
   { expect: import_expect.default },
   { intercept: (_method, path) => path[0] !== "expect" }
 ).expect;
-expect.extend(matchers);
+expect.extend(matchers?.default ?? matchers);
```

It makes me think that the issues is in relation to:
https://www.typescriptlang.org/tsconfig#esModuleInterop

Do you use modules or commonjs?

**Comment by IanVS** [comment]
Is everyone having this problem using the react-webpack Storybook framework?

**Comment by kaelig** [comment]
Affirmative, we're using a mix of React/Webpack/SWC/Babel and ran into this issue.

**Comment by yoshiko-pg** [comment]
Same as above.
I think the cause is this https://github.com/storybookjs/jest/commit/1d0a393d542d26b2ce7ee5bc4827a7795f61fc44 change.

Here is what else I use in my environment:
```
    "@storybook/nextjs": "7.4.5",
    "@storybook/react": "7.4.5",
    "@storybook/testing-library": "0.2.1",
```

**Comment by yannbf** [comment]
Hey everyone! thank you so much for reporting this issue.
I just made a release of v0.2.3 which should contain a fix for this. Could you please try it out? Thanks!
