### ISSUE TITLE
Module parse failed: Unexpected token on compile

### ISSUE THREAD

**Issue by borishuseincehajic** [storybookjs/jest#46]
**Describe the bug**

Compile error happening after using expect() in the storybook Play interaction. I tried changing versions of testing-library as well as adobe/css-tools but to no avail.

If I'm not using expect() everything is working fine.

**To Reproduce**
1. Install any @storybook/jest version with the below system setup
2. Create story and simple test using expect from@storybook/jest
3. Run storybook
See error 
`ERROR in ./node_modules/@adobe/css-tools/dist/index.mjs 96:23
 Module parse failed: Unexpected token (96:23)
 You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See 
 https://webpack.js.org/concepts#loaders`

**Expected behavior**
Success compile 

**System**
Please paste the results of `npx storybook@latest info` here.

```
Environment Info:

  System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
  Browsers:
    Chrome: 117.0.5938.92
    Safari: 15.6.1
  npmPackages:
    @storybook/addon-a11y: ^6.5.15 => 6.5.15
    @storybook/addon-actions: ^6.5.15 => 6.5.15
    @storybook/addon-essentials: ^6.5.15 => 6.5.15
    @storybook/addon-interactions: ^6.5.15 => 6.5.15
    @storybook/addon-links: ^6.5.15 => 6.5.15
    @storybook/builder-webpack4: ^6.5.15 => 6.5.15
    @storybook/jest: ^0.2.1 => 0.2.1
    @storybook/manager-webpack4: ^6.5.15 => 6.5.15
    @storybook/preset-scss: ^1.0.3 => 1.0.3
    @storybook/test-runner: ^0.9.4 => 0.9.4
    @storybook/testing-library: ^0.0.13 => 0.0.13
    @storybook/vue: ^6.5.15 => 6.5.15
```

**Additional context**
- N/A

**Comment by IanVS** [comment]
My guess is that webpack 4 does not support package.json 'exports' fields.  Do you know if it does?

If not, you'll need to use `@storybook/jest@0.1.x`, or upgrade to Storybook 7 / webpack 5 (though there's another issue with webpack and this package currently, that I need to investigate more).

**Comment by borishuseincehajic** [comment]
Makes sense for the webpack 4 as it does not support it. I know they've added it to webpack 5. 
I tried using `@storybook/jest@0.1.x` but will hit additional errors then like:


```
ERROR in ./node_modules/@storybook/expect/dist/index.mjs 1:121012
Module parse failed: Unexpected token (1:121012)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

(Source code omitted for this binary file)
ERROR in ./node_modules/@storybook/jest/node_modules/@storybook/instrumenter/dist/index.mjs 6:3158
Module parse failed: Unexpected token (6:3158)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import { global } from '@storybook/global';
| 
> var CallStates=(CallStates2=>...}
| 
| export { CallStates, EVENTS, instrument };

ERROR in ./node_modules/@adobe/css-tools/dist/index.mjs 96:23
Module parse failed: Unexpected token (96:23)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|                 line: lineno,
|                 column: column
>             }, options?.source || "");
|             whitespace();
|             return node;
```

**Comment by yannbf** [comment]
> If not, you'll need to use @storybook/jest@0.1.x, or upgrade to Storybook 7 / webpack 5 (though there's another issue with webpack and this package currently, that I need to investigate more).

I'm happy to say that this is not the case anymore in version 0.2.3!

@borishuseincehajic are you stuck with Webpack 4 in your project? I'd highly suggest migrating to Webpack5, so you can take full advantage of Storybook 7, but also to keep your project up to date. I know things are not easy in certain projects, but I hope you can!

**Comment by elclanrs** [comment]
@borishuseincehajic I'm getting that exact error including the same line number and everything:

`Module parse failed: Unexpected token (1:121012)`

Were you able to fix it?

I also tried 0.2.x, 0.1.x, 0.0.x. Same error. I'm using pnpm if that makes a difference.

**Comment by borishuseincehajic** [comment]
@elclanrs for me it was not the issue with that one but webpack not being able to handle certain imports properly. i found that one by someone from webpack repo in the end. My version of webpack is 4.6.x. Since I couldn't change the webpack version I decided to postpone these until I get the possibility to switch from wepback to vite

**Comment by IGCraig** [comment]
@elclanrs Did you ever solve this issue?

**Comment by elclanrs** [comment]
@IGCraig yes, we updated to the latest storybook and webpack.

**Comment by borishuseincehajic** [comment]
@elclanrs sorry for the late reply but did the same as you in the end.

**Comment by yannbf** [comment]
Hey everyone! In Storybook 8, this package functionality has been integrated to a new package called `@storybook/test`, which uses Vitest APIs for an improved experience. This issue should be solved or maybe it's not applicable anymore.

When upgrading to Storybook 8 with `npx storybook@latest upgrade`, you will get prompted and will get an automigration for the new package. Please migrate when you can! Thanks a lot <3
