### ISSUE TITLE
[bug] @storybook/jest breaks PHPStorm Inspections

### ISSUE THREAD

**Issue by hettiger** [storybookjs/jest#49]
**Describe the bug**
Angular uses Jasmine and PHPStorm Inspections work without `@storybook/jest`. Using just Angular + `@storybook/storybook` is also working fine. However, once you start using `@storybook/jest` PHPStorm starts to think that all `*.spec.ts` files are Jest tests instead of Jasmine ones. It's easily reproducible in a fresh Angular install.

**To Reproduce**
1. Use e.g. the `toHaveBeenCalledOnceWith` matcher in a Angular spec file
2. `import { expect } from '@storybook/jest';` and use it in a stories file
3. Go back to the Angular spec file
4. See PHPStorm error

![2023-10-13 14 41 05](https://github.com/storybookjs/jest/assets/4583871/95c80925-d2cf-49a0-b23e-3c0fc7153001)

**Expected behavior**
Ideally there should be no errors and PHPStorm should just get it automatically. However, this is probably not going to happen. Maybe Storybook team could add some notes to the docs providing more information. E.g. that `@storybook/jest` is not compatible with Angular or how to work around the described issues. Alternatively there might be a `@storybook/jasmine` for Angular users.

**Screenshots**
<img width="945" alt="image" src="https://github.com/storybookjs/jest/assets/4583871/ff65e817-9147-407a-a1e3-d222e0289cf6">

**System**
```
Environment Info:

  System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Chrome: 117.0.5938.149
    Safari: 17.0
  npmPackages:
    @storybook/addon-docs: ^7.4.6 => 7.4.6
    @storybook/addon-essentials: ^7.4.6 => 7.4.6
    @storybook/addon-interactions: ^7.4.6 => 7.4.6
    @storybook/addon-links: ^7.4.6 => 7.4.6
    @storybook/angular: ^7.4.6 => 7.4.6
    @storybook/blocks: ^7.4.6 => 7.4.6
    @storybook/jest: ^0.2.3 => 0.2.3
    @storybook/testing-library: ^0.2.2 => 0.2.2
```

**Additional context**
–

**Comment by hettiger** [comment]
Found a workaround:

Add `/// <reference types="@types/jasmine" />` to the Angular `test.ts` file.

**Comment by yannbf** [comment]
Hey everyone! In Storybook 8, this package functionality has been integrated to a new package called `@storybook/test`, which uses Vitest APIs for an improved experience. This issue should be solved or maybe it's not applicable anymore.

When upgrading to Storybook 8 with `npx storybook@latest upgrade`, you will get prompted and will get an automigration for the new package. Please migrate when you can! Thanks a lot <3
