### ISSUE TITLE
feat: support @testing-library/jest-dom

### ISSUE THREAD

**Issue by robcaldecott** [storybookjs/jest#7]
Being able to run `expect` style assertions in our `play` functions is pretty awesome but it would be great if we had access to the `jest-dom` helpers that we're using in our tests: `toBeInTheDocument`, `toHaveValue`, `toBeVisible` and so on.

https://github.com/testing-library/jest-dom

For example:

```tsx
Filtered.play = async (context) => {
  const canvas = within(context.canvasElement);
  const input = await canvas.findByRole("textbox");
  await userEvent.type(input, "volk");
  expect(await canvas.findByText("volkswagen")).toBeInTheDocument();
};
```

**Comment by yannbf** [comment]
Hey @robcaldecott I'm happy to announce that this has been implemented and you can access it by upgrading your `@storybook/jest` dependency to `0.0.9`! You might have to delete your package-lock or yarn.lock files as this library depends on `@storybook/expect` and should use its latest version `27.5.2-0`.
