### ISSUE TITLE
[Bug] Exported type for expect function

### ISSUE THREAD

**Issue by FTWinston** [storybookjs/jest#8]
### Describe the bug

Using `expect`, as exported by `@storybook/jest`, triggers failures in the `@typescript-eslint/no-unsafe-member-access` and `@typescript-eslint/no-unsafe-call` rules. Using the `@storybook/expect` version does not.

Confusingly, if I create a local copy of all of the `@storybook/jest` and call that version instead, this works correctly.

### Steps to reproduce the behavior

1. Ensure project has eslint running, using `plugin:@typescript-eslint/recommended`
2. Create a new story, and in its `play` function, call `expect` from `@storybook/expect`.
2. Note that no eslint errors are shown.
3. Replace `import expect from '@storybook/expect'` with `import { expect } from '@storybook/jest'`
4. Not that `expect` calls now show eslint errors for `@typescript-eslint/no-unsafe-member-access` and `@typescript-eslint/no-unsafe-call`
5. Copy all of `@storybook/jest`'s code into a local `jest.ts` file, and replace `import { expect } from '@storybook/jest'` with `import { expect } from './jest'`
6. Note that no eslint errors are shown.

### Expected behavior

None of the three cases described above should show these eslint errors.

The exported type definitions for `@storybook/jest` are:

```
import * as mock from 'jest-mock';
export declare const jest: typeof mock;
export declare const expect: import("expect/build/types").Expect<import("expect/build/types").MatcherState>;
```

Eslint (as well as VSCode's intellisense) seems to interpret the type of this `expect` as `any`.

It should instead have the same type as the `expect` exported from `@storybook/expect` (and it does... but only if I copy the `@storybook/jest` code locally).

### Screenshots and/or logs

For this line:
```    expect(canvas.queryByText('Message')).not.toBeNull();```

We get
```
  Line 40:5:  Unsafe member access .not on an `any` value  @typescript-eslint/no-unsafe-member-access
  Line 40:5:  Unsafe call of an `any` typed value          @typescript-eslint/no-unsafe-call
  Line 40:5:  Unsafe call of an `any` typed value          @typescript-eslint/no-unsafe-call
```

### Environment

 - OS: Windows
 - Node.js version: v16.13.0
 - NPM version: 8.1.0
 - Browser (if applicable): N/A
 - Browser version (if applicable): N/A
 - Device (if applicable): N/A

### Additional context

_Possibly_ caused by the esm compile target being ES5? I'll try and check this.

**Comment by yannbf** [comment]
Fixed in #9. Thanks a lot @FTWinston!
